//This file is autogenerated from Tink2FManII.py

//If you value your sanity do not try to manually edit it!!!

#pragma once
#include<vector>
#include<ForceManII/FManII.hpp>
extern const std::vector<double> deltorphin;
extern const FManII::IVector deltorphin_FF_types;
extern const FManII::ConnData deltorphin_conns;
extern const std::vector<double> deltorphin_bonds;
extern const std::vector<double> deltorphin_angles;
extern const std::vector<double> deltorphin_torsions;
extern const std::vector<double> deltorphin_imptorsion;
extern const std::vector<double> deltorphin_pairs;
extern const std::vector<double> deltorphin_K;
extern const std::vector<double> deltorphin_r0;
extern const std::vector<double> deltorphin_angle_K;
extern const std::vector<double> deltorphin_angle_r0;
extern const std::vector<double> deltorphin_torsion_v;
extern const std::vector<double> deltorphin_imptorsion_v;
extern const std::vector<double> deltorphin_charge_q;
const double deltorphinelectrostatics_e=-0.4331619787171384;
const double deltorphinangle_e=0.3681218582153962;
const double deltorphintorsion_e=0.5242947677613219;
const double deltorphinbond_e=0.20876174643383943;
