//This file is autogenerated from FindIntCoordsFF.py

//If you value your sanity do not try to manually edit it!!!

#pragma once
#include<ForceManII/FManII.hpp>
extern const std::map<FManII::IntCoord_t,FManII::Vector> ubiquitin_qs;
