//This file is autogenerated from MakeTest.py

//If you value your sanity do not try to manually edit it!!!

#pragma once
#include<vector>
#include<ForceManII/FManII.hpp>
extern const FManII::Vector ubiquitin;
extern const FManII::IVector ubiquitin_FF_types;
extern const FManII::ConnData ubiquitin_conns;
const double ubiquitinimproper_e=0.04397335116466744;
const double ubiquitinelectrostatics_e=-3.9402485635279523;
const double ubiquitinvdw_e=-0.4313795358668616;
const double ubiquitintorsion_e=1.1247544260677447;
const double ubiquitinbond_e=0.6714565004264477;
const double ubiquitinangle_e=0.9503986871276552;
