//This file is autogenerated from Tink2FManII.py

//If you value your sanity do not try to manually edit it!!!

#pragma once
#include<vector>
#include<ForceManII/FManII.hpp>
extern const std::vector<double> ubiquitin;
extern const FManII::AtomTypes ubiquitin_FF_types;
extern const FManII::ConnData ubiquitin_conns;
extern const std::vector<double> ubiquitin_bonds;
extern const std::vector<double> ubiquitin_angles;
extern const std::vector<double> ubiquitin_torsions;
extern const std::vector<double> ubiquitin_imptorsion;
extern const std::vector<double> ubiquitin_pairs;
extern const FManII::ParamTypes ubiquitin_FF_params;
extern const std::vector<double> ubiquitin_K;
extern const std::vector<double> ubiquitin_r0;
extern const std::vector<double> ubiquitin_angle_K;
extern const std::vector<double> ubiquitin_angle_r0;
extern const std::vector<double> ubiquitin_torsion_v;
extern const std::vector<double> ubiquitin_imptorsion_v;
extern const std::vector<double> ubiquitin_charge_q;
const double ubiquitinvdw_e=-0.4313795358668616;
const double ubiquitintorsion_e=1.1247544260677447;
const double ubiquitinbond_e=0.6714565004264477;
const double ubiquitinelectrostatics_e=-3.9402485635279523;
const double ubiquitinimproper_e=0.04397335116466744;
const double ubiquitinangle_e=0.9503986871276552;
