//This file is autogenerated from MakeTest.py

//If you value your sanity do not try to manually edit it!!!

#pragma once
#include<vector>
#include<ForceManII/FManII.hpp>
extern const FManII::Vector crambin;
extern const FManII::IVector crambin_FF_types;
extern const FManII::ConnData crambin_conns;
extern const std::map<FManII::FFTerm_t,double> crambin_egys;
