//This file is autogenerated from FindIntCoordsFF.py

//If you value your sanity do not try to manually edit it!!!

#pragma once
#include<ForceManII/FManII.hpp>
extern const std::map<std::string,FManII::Vector> peptide_qs;
