//This file is autogenerated from MakeTest.py

//If you value your sanity do not try to manually edit it!!!

#pragma once
#include<vector>
#include<ForceManII/FManII.hpp>
extern const FManII::Vector peptide;
extern const FManII::IVector peptide_FF_types;
extern const FManII::ConnData peptide_conns;
extern const std::map<FManII::FFTerm_t,double> peptide_egys;
