//This file is autogenerated from MakeTest.py

//If you value your sanity do not try to manually edit it!!!

#pragma once
#include<vector>
#include<ForceManII/FManII.hpp>
extern const FManII::Vector ubiquitin;
extern const FManII::IVector ubiquitin_FF_types;
extern const FManII::ConnData ubiquitin_conns;
extern const std::map<FManII::FFTerm_t,double> ubiquitin_egys;
